### PR TITLE
add tests on github workflows for ubuntu

### PR DESCRIPTION
**Pull request by tlambert03**
Pre-Merge Checklist:

- [ ] if this PR adds a feature: request merge into the latest development branch (`vX.Y-dev`)
- [x] if this PR fixes a bug: request merge into the latest patch branch (`patch-X.Y.Z`)
- [x] PR branch name is short and describes the feature/bug addressed in this PR
- [x] commit messages [are consistent](https://chris.beams.io/posts/git-commit/)
- [ ] changes reviewed by another contributor
- [ ] tests cover changes
- [ ] all tests pass

If I'm not mistaken, the travis tests here haven't been running for a while (last build is [~ a year ago](https://travis-ci.org/github/funkey/gunpowder/builds)).  This PR would add tests using github workflows for python 3.6-3.10 on ubuntu.

I can add macos and/or windows, but from some quick tests, they are each failing and would need a few additional fixes to work.  It also appears that there are some non-deterministic fails in `TestShiftAugment2D.test_pipeline2` ... see the [three attempts here](https://github.com/tlambert03/gunpowder/actions/runs/3015813537/), where they [all passed on attempt 2](https://github.com/tlambert03/gunpowder/actions/runs/3015813537/attempts/2), but at least one failed on `test_pipeline2` in the other runs.  I'll let this run to see how it goes here, and if you're interested in adding these tests, we can determine how to fix that random fail

### CODE REVIEW

**Comment by pattonw** [comment]
Great! Thanks Talley. I like the code coverage bot. I think we should go ahead and switch to github actions. We can remove the travis.yaml in that case

**Comment by tlambert03** [comment]
cool.  would you like me to try to nail down the sporadic `TestShiftAugment2D.test_pipeline2` out-of-ROI fail here?  or leave that for a different PR?

**Comment by pattonw** [comment]
If you want to take a stab at it here that would be greatly appreciated. Otherwise I'm all for merging sooner rather than later and leaving the sporadic failure fix to another pull request

**Comment by tlambert03** [comment]
I had a look, but I think someone more familiar with `ShiftAugment.construct_global_shift_array` should probably have a look.  I can tell you that the `TestShiftAugment2D.test_pipeline2` test fails every time `ShiftAugment.construct_global_shift_array` returns a value where index `(0, 1)` is positive (i.e.  when `shift_array == [[0,1,]]` or `shift_array == [[0,2,]]`) ... Furthermore, that pretty much always happens when `r <= prob_slip`

but I'm afraid the intention of that method isn't super clear to me... so I hesitate to try to fix it.

**Comment by pattonw** [comment]
Ok, I'm going to go ahead and merge this and we can leave the `ShiftAugment` sporadic fails for a future pull request

**Pull request merged**
