### PR TITLE
Update random_location.py

### PR DESCRIPTION
**Pull request by yajivunev**
removed dtype argument in skimage.transform.integral_image

### CODE REVIEW

**Comment by abred** [comment]
integral_image can change the dtype, maybe
```
self.mask_integral = integral_image(self.mask_integral).astype(mask_integral_dtype)
```
would be good then.

**Comment by benjamin9555** [comment]
Just ran into the same issue. I can't trace back at which point the `dtype` parameter was removed from looking at the skimage docs, so pinning skimage is not the easy way out here.

**Comment by pattonw** [comment]
I just ran into this too

**Comment by pattonw** [comment]
Added Peter's suggestion and merged it on commit: 457c4e597162b29a338dc4598c6037c11bdd3bc9
not sure why it didn't automatically detect this pull request as merged

**Pull request closed without merging**
