### PR TITLE
Add option to use custom predict graph

### PR DESCRIPTION
**Pull request by nilsec**

### CODE REVIEW

**Comment by nilsec** [comment]
It seems the tensorflow_train test fails. This commit doesn't touch the training node at all though. What's going wrong?

**Comment by funkey** [comment]
Maybe I am missing something, but how is this different from the current implementation, except that you don't assume that the meta graph file ends with `.meta`?

Regarding the `tensorflow` test, this was unrelated to your changes. Fixed in 9bc53a59c527463f426116f1523824dda5619045.

**Comment by nilsec** [comment]
It's different since the meta graph you specify can be arbitrary now and not the one corresponding to a  certain checkpoint. Only the variables with the same name are restored from the checkpoint. Somehow I need to tell gunpowder that I don't want to restore the .meta graph in my train directory, or is there an easy way to do that already implemented that I'm not seeing?

**Comment by funkey** [comment]
Thanks a lot!

**Pull request merged**
