### PR TITLE
z5py-based batch providers

### PR DESCRIPTION
**Pull request by clbarnes**
Someone mentioned it would be nice to have an N5 batch provider, so here it is (along with zarr, because that comes for free with z5py).

I've just factored all the hdf5source logic (for implementation and tests) into a base class and made thin subclasses which support hdf5, n5 and zarr. The n5 and zarr tests automatically skip if z5py isn't available. If we want to run those tests in CI it means using conda, which means no tox (sadface). My bad, I can switch back to conda if required.

Currently these changes depend on an unreleased version of z5py, but I've asked Constantin very nicely so maybe it will be released soon :)

### CODE REVIEW

**Comment by clbarnes** [comment]
Oops, messed up the git history. Now with tests!

**Comment by funkey** [comment]
Thanks a lot.

I suggest we put each of the concrete sources in individual files. It reads a bit odd to say `from gunpowder.hdf5_source import N5Source`.

What is the purpose of `infer_source_type`? I don't see it used anywhere. Is your idea to replace the `Hdf5Source` with `Hdf5LikeSource`, and any file name can be given? That might not work in general, as N5 and zarr "files" are directories that do not necessarily have an extension.

Also, please avoid whitespace edits.

**Comment by clbarnes** [comment]
> I suggest we put each of the concrete sources in individual files. It reads a bit odd to say from gunpowder.hdf5_source import N5Source.

Agreed.

> What is the purpose of infer_source_type? I don't see it used anywhere. Is your idea to replace the Hdf5Source with Hdf5LikeSource, and any file name can be given? That might not work in general, as N5 and zarr "files" are directories that do not necessarily have an extension.

True. It was mainly just that given the logic was generic over those data source types it might be a useful shorthand. If someone gave it a path without one of those extensions it'd just throw a KeyError anyway. Explicit being better than implicit, and what with splitting the sources out into their own files, I can remove it.

> Also, please avoid whitespace edits.

Sorry, I think that was my IDE.

Constantin's released the relevant version of z5py so once I've fixed those points, this could be merged. Shall I switch the travis build back to conda so that we can run the tests on the new sources in CI? The logic and tests are all identical to the Hdf5Source, which is tested, but it's probably still best to actually run them.

**Comment by clbarnes** [comment]
This is blocked by a z5py bug, fixed here: https://github.com/constantinpape/z5/pull/38

It's still failing to import z5py for the moment but I'll assume it's related until the PR is in.

**Comment by clbarnes** [comment]
Note: https://github.com/constantinpape/z5#a-note-on-axis-ordering

z5py effectively transposes data from xyz into zyx on the way out. Built-in attributes like `shape` are handled internally, but user-set attributes will not be. Specifically, `resolution` and `offset` will be one way round if the data was created with z5py (and the creator didn't take care to flip them on the way in) and the other way round if created with the reference implementation. It should probably be flipped on the way out, on the assumption that the user has taken due care in the creation of the dataset.

**Comment by funkey** [comment]
What is the state of this PR? Still blocked by the z5py release?

**Comment by clbarnes** [comment]
Yeah, sorry, this is pretty stale now.

There is a runtime glibc dependency which will make the tests fail and I'm not sure whether it's possible to fix that on the z5py side https://github.com/constantinpape/z5/issues/43

Is master the right branch to rebase on now?

**Comment by funkey** [comment]
Yes, the master branch is the right one to rebase on.

**Comment by clbarnes** [comment]
OK, here's the situation.

As per https://github.com/constantinpape/z5/issues/43 , on travis, z5py won't install from conda properly, due to some compiled - most likely something which would be pulled in by installing a more recent GCC version than either travis or conda has by default.

However, using a minimal example here https://github.com/clbarnes/z5_boost_bug/tree/libgcc-fix I can only trigger this type of failure on py3.4. Python 2.7 works fine on that test repo. I considered that maybe the mixture of pip/conda installs in gunpowder was the issue, but that shouldn't affect the existence of compiled libraries given the conda install of z5py is done first. I'm kind of stumped.

I've done the rebase on master, and I can run the z5-based provider tests fine locally, so it works, and the tests skip rather than fail the build if z5py doesn't install properly. But "it's fine locally" isn't what CI is for :P

**Comment by funkey** [comment]
@clbarnes, does that mean we can run the z5 CI test on python2.7 at least?

**Comment by clbarnes** [comment]
The z5_boost_bug test repo works on py2.7 (along with 3.5 and 3.6). the gunpowder z5-based tests fail (or rather, skip, because that's what they do when z5py isn't installed) on py2.7, with the same error as the z5_boost_bug repo does on py3.4.

The gunpowder z5-based tests run fine locally, on py2.7, with a clean conda environment. I'll experiment a bit more today but it's a head-scratcher.

**Comment by funkey** [comment]
I suggest we remove the the "do not merge" warning, merge, and open an issue about the skipped test instead.

Also, I just created a branch `release-v1.0`. Would you mind rebasing the PR on that instead of `master`? Thanks a lot!

**Comment by clbarnes** [comment]
There are a couple of subjective changes in the last few commits: firstly, I've renamed `test_suite.py` to `__main__.py` which allows people to just `python -m tests`, as well as passing it arguments to change the verbosity (`-vv` etc.). I also changed the `print`s in the tests to logs, and used `skipIf` rather than guard clauses for tests dependent on inaccessible extras (malis, DVID etc.) - this makes the output cleaner and more informative.

I'm going to write some docs for the new sources too.

**Comment by clbarnes** [comment]
This can go in; I have a local commit which adds `autoclass` statements to `nodes.rst.txt` for `N5Source` and `ZarrSource` but I'm not sure whether I need to run something else to get jekyll to turn that into HTML. Maybe a make recipe would be helpful for that?

**Comment by funkey** [comment]
Thanks a lot!

Regarding the docs: There is a `Makefile` in `docs/build` which will create the HTML. For now, it won't be necessary to do so, though. I am currently rewriting and consolidating the docs in branch `update_docs`. Creating HTML now will only introduce noise that later has to be merged.

**Pull request merged**
