### PR TITLE
Jitter node

### PR DESCRIPTION
**Pull request by cmalinmayor**
Adds implementation of a jitter node that works in n-dimensions.

### CODE REVIEW

**Comment by hanslovsky** [comment]
@cmalinmayor I have a [elastic_augment implementation for arbitrary voxel sizes](https://github.com/hanslovsky/gunpowder-nodes/blob/master/gpn/elastic_augment.py) as well. We should probably get together and see what the differences are. Do you have time this afternoon (Monday, 11/12)?

**Comment by hanslovsky** [comment]
Let's do 1:30

**Comment by hanslovsky** [comment]
Protocol of our meeting:
We had a different understanding of the term *jitter*: 
 - @cmalinmayor implemented a node that adds an offset for each slice (i.e. `data[..., slice_index, ...]`) that is constant for all voxels within a slice but varies across slices.
 - @hanslovsky referred to jitter as in the terms of `jitter_sigma` in the `ElasticAugment` node.

Conclusion: We did not implement the same node twice. @hanslovsky will change the name of the `jitter_sigma` parameter to avoid further confusion.

**Comment by funkey** [comment]
Looks good to me. Please rename to `ShiftAugment` and we are ready to merge.

**Comment by funkey** [comment]
Thanks a lot!

**Pull request merged**
